version: '3.4'
services:
  weaviate:
    image: semitechnologies/weaviate:1.18.3
    command:
      - --host
      - 0.0.0.0
      - --port
      - '2000'
      - --scheme
      - http
    ports:
      - "2000:2000"
    restart: on-failure:0
    environment:
      PROMETHEUS_MONITORING_ENABLED: 'true'
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: text2vec-transformers
      ENABLE_MODULES: text2vec-transformers,qna-transformers
      TRANSFORMERS_INFERENCE_API: http://t2v-transformers:8080
      QNA_INFERENCE_API: "http://qna-transformers:8080"
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - /var/weaviate:/var/lib/weaviate
  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-msmarco-distilroberta-base-v2
    environment:
      ENABLE_CUDA: 0
  qna-transformers:
    image: semitechnologies/qna-transformers:bert-large-uncased-whole-word-masking-finetuned-squad
    environment:
      ENABLE_CUDA: 0
