spring:
  config:
    activate:
      on-profile: default
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 80
weaviate:
  hostname: 'weaviate'
  port: '2000'
search:
  alpha: 0.5
  preprocess: true
data.path: 'data/sites'
